apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-microservice
  namespace: fwutter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80