apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-microservice
  name: frontend-microservice
  namespace: development
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend-microservice
  type: ClusterIP